/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI.Panel;

import BUS.NganhBUS;
import BUS.ToHopNganhBUS;
import DTO.ToHopNganhDTO;
import GUIDialog.AddToHopNganhDialog;
import GUIDialog.UpdateToHopNganhDialog;
import com.formdev.flatlaf.extras.FlatSVGIcon;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Font;
import java.awt.Frame;
import java.awt.Window;
import java.io.File;
import java.util.ArrayList;
import javax.swing.BorderFactory;
import javax.swing.JDialog;
import javax.swing.JFileChooser;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.SwingWorker;
import javax.swing.table.TableColumnModel;
import org.jdesktop.swingx.prompt.PromptSupport;
import util.Combobox_design;
import util.JButton_design;
import util.JTextF_design;
import util.Table_design;

/**
 *
 * @author kiman
 */
public class ToHopNganhPanel extends javax.swing.JPanel {
    Combobox_design cbb_design = new Combobox_design();
    ToHopNganhBUS toH_ng_Bus = new ToHopNganhBUS();
    Table_design table_design = new Table_design();
    NganhBUS nganhBus = new NganhBUS();
    JTextF_design jtf_design = new JTextF_design();
    JButton_design btn_design = new JButton_design();
    /**
     * Creates new form ToHopNganhPanel
     */
    public ToHopNganhPanel() {
        initComponents();
        khoiTao();
    }
    public void khoiTao() {
        dataTable(toH_ng_Bus.getAll());
        setUpJtf();
        setIcon();
        setUpBtn();
    }

    
    public void setUpJtf(){
        jtf_design.setUpJTF(jtf_timkiem);
        PromptSupport.setPrompt("Tìm kiếm theo tên ngành, mã ngành, mã tổ hợp", jtf_timkiem);
        PromptSupport.setForeground(Color.GRAY, jtf_timkiem);
        PromptSupport.setFocusBehavior(PromptSupport.FocusBehavior.SHOW_PROMPT, jtf_timkiem);
    }
    public void setUpBtn(){
        btn_design.setUpBtn(btn_timkiem,Color.white,Color.white);
        btn_design.setUpBtn(btn_refresh,Color.white,Color.white);
    }
    public void setIcon(){
        btn_refresh.setIcon(new FlatSVGIcon("./resources/icon/refresh.svg",0.25f));
        btn_timkiem.setIcon(new FlatSVGIcon("./resources/icon/look.svg",0.25f));
        btn_add.setIcon(new FlatSVGIcon("./resources/icon/add.svg",0.2f));
        btn_update.setIcon(new FlatSVGIcon("./resources/icon/edit.svg",0.2f));
        btn_import.setIcon(new FlatSVGIcon("./resources/icon/import.svg",0.2f));
        btn_delete.setIcon(new FlatSVGIcon("./resources/icon/delete.svg",0.2f));
    }

    public void dataTable(ArrayList<ToHopNganhDTO> list) {

        DefaultTableModel model = new DefaultTableModel(
                new Object[][]{},
                new String[]{
                    "Mã ngành", "Tên ngành", "Mã tổ hợp",
                    "Môn 1", "HS1",
                    "Môn 2", "HS2",
                    "Môn 3", "HS3",
                    "Độ lệch"
                }
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        for (ToHopNganhDTO t : list) {

            String tenNganh = nganhBus.getTenNganhByMaNganh(t.getManganh());

            model.addRow(new Object[]{
                t.getManganh(),
                tenNganh, // thêm dòng này
                t.getMatohop(),
                t.getTh_mon1(), t.getHsmon1(),
                t.getTh_mon2(), t.getHsmon2(),
                t.getTh_mon3(), t.getHsmon3(),
                t.getDolech()
            });
        }

        combination_major_table.setModel(model);

        // ===== style bảng =====
        table_design.centerTable(combination_major_table);
        table_design.setUpTable(combination_major_table);

        TableColumnModel columnModel = combination_major_table.getColumnModel();

        columnModel.getColumn(0).setPreferredWidth(100); // mã ngành
        columnModel.getColumn(1).setPreferredWidth(150); // tên ngành
        columnModel.getColumn(2).setPreferredWidth(100); // mã tổ hợp

        columnModel.getColumn(3).setPreferredWidth(80);
        columnModel.getColumn(4).setPreferredWidth(50);
        columnModel.getColumn(5).setPreferredWidth(80);
        columnModel.getColumn(6).setPreferredWidth(50);
        columnModel.getColumn(7).setPreferredWidth(80);
        columnModel.getColumn(8).setPreferredWidth(50);

        columnModel.getColumn(9).setPreferredWidth(100);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        combination_major_table = new javax.swing.JTable();
        jtf_timkiem = new javax.swing.JTextField();
        btn_import = new javax.swing.JButton();
        btn_add = new javax.swing.JButton();
        btn_update = new javax.swing.JButton();
        btn_timkiem = new javax.swing.JButton();
        btn_refresh = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 204));
        setPreferredSize(new java.awt.Dimension(1008, 1008));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("HỆ THỐNG /");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 0));
        jLabel2.setText("TỔ HỢP - NGÀNH");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Quản lý tổ hợp - ngành");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        combination_major_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(combination_major_table);

        btn_import.setBackground(new java.awt.Color(204, 204, 255));
        btn_import.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_import.setForeground(new java.awt.Color(51, 51, 255));
        btn_import.setText("Import Excel");
        btn_import.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_importActionPerformed(evt);
            }
        });

        btn_add.setBackground(new java.awt.Color(0, 135, 51));
        btn_add.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_add.setForeground(new java.awt.Color(255, 255, 255));
        btn_add.setText("Thêm");
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });

        btn_update.setBackground(new java.awt.Color(52, 152, 219));
        btn_update.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_update.setForeground(new java.awt.Color(255, 255, 255));
        btn_update.setText("Sửa");
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });

        btn_timkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_timkiemActionPerformed(evt);
            }
        });

        btn_refresh.setText("Làm mới");
        btn_refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_refreshActionPerformed(evt);
            }
        });

        btn_delete.setBackground(new java.awt.Color(255, 0, 0));
        btn_delete.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_delete.setForeground(new java.awt.Color(255, 255, 255));
        btn_delete.setText("Xóa");
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jtf_timkiem, javax.swing.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_timkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_refresh, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(btn_import, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_add, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_update, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtf_timkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_timkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_add, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_update, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_import, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_refresh, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(22, 22, 22)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 838, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed
        Window parentWindow = SwingUtilities.getWindowAncestor(this);
        new AddToHopNganhDialog((Frame) parentWindow, true,this).setVisible(true);
    }//GEN-LAST:event_btn_addActionPerformed

    private void btn_importActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_importActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Chọn file Excel");

        int result = fileChooser.showOpenDialog(this);
        if (result != JFileChooser.APPROVE_OPTION) {
            return;
        }

        File file = fileChooser.getSelectedFile();
        String filePath = file.getAbsolutePath();

        // ===== LOADING DIALOG =====
        JDialog loadingDialog = new JDialog();
        loadingDialog.setTitle("Đang xử lý...");
        loadingDialog.setLayout(new BorderLayout());

        JLabel text = new JLabel("Đang import tổ hợp ngành...", JLabel.CENTER);
        text.setFont(new Font("Segoe UI", Font.BOLD, 14));
        text.setBorder(BorderFactory.createEmptyBorder(20, 20, 20, 20));

        loadingDialog.add(text, BorderLayout.CENTER);

        loadingDialog.pack();
        loadingDialog.setLocationRelativeTo(this);
        loadingDialog.setDefaultCloseOperation(JDialog.DO_NOTHING_ON_CLOSE);

        // ===== BACKGROUND TASK =====
        SwingWorker<Void, Void> worker = new SwingWorker<>() {

            int count = 0;
            String message = "";

            @Override
            protected Void doInBackground() {
                try {
                    count = toH_ng_Bus.importFromExcel(filePath);

                    if (count == 0) {
                        message = "File không có dữ liệu hoặc bị trùng!";
                    } else {
                        message = "Import thành công " + count + " tổ hợp ngành!";
                    }

                } catch (Exception e) {
                    e.printStackTrace();
                    message = "Lỗi khi import: " + e.getMessage();
                }
                return null;
            }

            @Override
            protected void done() {
                loadingDialog.dispose(); // tắt loading

                JOptionPane.showMessageDialog(null, message);

                // reload bảng
                dataTable(toH_ng_Bus.getAll());
            }
        };

        worker.execute();

        // hiển thị loading
        loadingDialog.setVisible(true);
    }//GEN-LAST:event_btn_importActionPerformed

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
        int row = combination_major_table.getSelectedRow();

        if (row == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Vui lòng chọn dòng cần sửa!");
            return;
        }

        ToHopNganhDTO dto = new ToHopNganhDTO();

        dto.setId(toH_ng_Bus.getIdbyIndex(row)); // cần viết hàm này trong BUS

        dto.setManganh(combination_major_table.getValueAt(row, 0).toString());
        dto.setMatohop(combination_major_table.getValueAt(row, 2).toString());

        dto.setTh_mon1(combination_major_table.getValueAt(row, 3).toString());
        dto.setHsmon1(Integer.parseInt(combination_major_table.getValueAt(row, 4).toString()));

        dto.setTh_mon2(combination_major_table.getValueAt(row, 5).toString());
        dto.setHsmon2(Integer.parseInt(combination_major_table.getValueAt(row, 6).toString()));

        dto.setTh_mon3(combination_major_table.getValueAt(row, 7).toString());
        dto.setHsmon3(Integer.parseInt(combination_major_table.getValueAt(row, 8).toString()));

        dto.setDolech(new java.math.BigDecimal(combination_major_table.getValueAt(row, 9).toString()));

        Window parent = SwingUtilities.getWindowAncestor(this);
        new UpdateToHopNganhDialog((Frame) parent, true, this, dto).setVisible(true);
    }//GEN-LAST:event_btn_updateActionPerformed

    private void btn_timkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_timkiemActionPerformed
        String text = jtf_timkiem.getText();
        dataTable(toH_ng_Bus.timkiemText(text));

    }//GEN-LAST:event_btn_timkiemActionPerformed

    private void btn_refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_refreshActionPerformed
        jtf_timkiem.setText("");
        dataTable(toH_ng_Bus.getAll());
    }//GEN-LAST:event_btn_refreshActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_deleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_import;
    private javax.swing.JButton btn_refresh;
    private javax.swing.JButton btn_timkiem;
    private javax.swing.JButton btn_update;
    private javax.swing.JTable combination_major_table;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jtf_timkiem;
    // End of variables declaration//GEN-END:variables
}
