/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI.Panel;

import BUS.ToHopBUS;
import DTO.ToHopDTO;
import GUIDialog.AddToHopDialog;
import java.awt.Frame;
import java.awt.Window;
import java.util.ArrayList;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import util.JTextF_design;
import util.Table_design;


/**
 *
 * @author kiman
 */
public class TohopPanel extends javax.swing.JPanel {
    JTextF_design jtf_design = new JTextF_design();
    ToHopBUS tohopBus = new ToHopBUS();
    Table_design table_design = new Table_design();
    /**
     * Creates new form TohopPanel
     */
    public TohopPanel() {
        initComponents();
        khoiTao();
    }
    public void khoiTao(){
        dataTable(tohopBus.getListTH());
        designJTF();
    }
    public void designJTF(){
        jtf_design.setUpJTF(jTextField1);
        jtf_design.setUpJTF(jTextField2);
    }
    public void dataTable(ArrayList<ToHopDTO> listToHop) {
        DefaultTableModel model = new DefaultTableModel(
                new Object[][]{},
                new String[]{"Mã tổ hợp", "Môn 1", "Môn 2", "Môn 3", "Tên tổ hợp"}
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        for (ToHopDTO t : listToHop) {
            model.addRow(new Object[]{
                t.getMatohop(),
                t.getMon1(),
                t.getMon2(),
                t.getMon3(),
                t.getTentohop()
            });
        }

        combination_table.setModel(model);

        //format giống bảng ngành
        table_design.centerTable(combination_table);
        table_design.setUpTable(combination_table);

        TableColumnModel columnModel = combination_table.getColumnModel();
        columnModel.getColumn(0).setPreferredWidth(100); // mã
        columnModel.getColumn(1).setPreferredWidth(80);  // môn 1
        columnModel.getColumn(2).setPreferredWidth(80);  // môn 2
        columnModel.getColumn(3).setPreferredWidth(80);  // môn 3
        columnModel.getColumn(4).setPreferredWidth(200); // tên tổ hợp
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        combination_import = new javax.swing.JButton();
        combination_add = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        combination_table = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        combination_filter = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("HỆ THỐNG /");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 204, 51));
        jLabel2.setText(" TỔ HỢP MÔN");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabel3.setText("Quản lý Tổ hợp môn");

        combination_import.setBackground(new java.awt.Color(204, 204, 255));
        combination_import.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        combination_import.setForeground(new java.awt.Color(51, 51, 255));
        combination_import.setText("Import Excel");
        combination_import.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combination_importActionPerformed(evt);
            }
        });

        combination_add.setBackground(new java.awt.Color(0, 153, 51));
        combination_add.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        combination_add.setForeground(new java.awt.Color(255, 255, 255));
        combination_add.setText("Thêm tổ hợp");
        combination_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combination_addActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(combination_import, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(combination_add)
                .addGap(26, 26, 26))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addGap(8, 8, 8))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(combination_import, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combination_add, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        combination_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(combination_table);

        jLabel4.setText("Mã tổ hợp");

        jLabel5.setText("Tên tổ hợp");

        combination_filter.setBackground(new java.awt.Color(0, 0, 255));
        combination_filter.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        combination_filter.setForeground(new java.awt.Color(255, 255, 255));
        combination_filter.setText("Lọc dữ liệu");
        combination_filter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combination_filterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                        .addComponent(combination_filter, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))))
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(combination_filter, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void combination_importActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combination_importActionPerformed
        try {
            javax.swing.JFileChooser fileChooser = new javax.swing.JFileChooser();
            fileChooser.setDialogTitle("Chọn file Excel");

            int result = fileChooser.showOpenDialog(this);

            if (result == javax.swing.JFileChooser.APPROVE_OPTION) {
                java.io.File file = fileChooser.getSelectedFile();

                //  GỌI BUS
                int count = tohopBus.importFromExcel(file.getAbsolutePath());

                if (count == 0) {
                    javax.swing.JOptionPane.showMessageDialog(this, "File không có dữ liệu!");
                    return;
                }

                // reload table
                dataTable(tohopBus.getListTH()); 

                javax.swing.JOptionPane.showMessageDialog(this,
                        "Import thành công " + count + " tổ hợp!");
            }

        } catch (Exception e) {
            e.printStackTrace();
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Lỗi khi import: " + e.getMessage());
        }
    }//GEN-LAST:event_combination_importActionPerformed

    private void combination_filterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combination_filterActionPerformed
        String maTH = jTextField1.getText();
        String tenTH = jTextField2.getText();
        dataTable(tohopBus.timkiem(maTH, tenTH));
    }//GEN-LAST:event_combination_filterActionPerformed

    private void combination_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combination_addActionPerformed
        Window parentWindow = SwingUtilities.getWindowAncestor(this);
        new AddToHopDialog((Frame) parentWindow, true,this).setVisible(true);
    }//GEN-LAST:event_combination_addActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton combination_add;
    private javax.swing.JButton combination_filter;
    private javax.swing.JButton combination_import;
    private javax.swing.JTable combination_table;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
