/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package GUIDialog;

import BUS.ThiSinhBUS;
import DTO.ThiSinhDTO;
import GUI.Panel.ThiSinhPanel;
import com.formdev.flatlaf.extras.FlatSVGIcon;
import java.awt.Color;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import org.jdesktop.swingx.prompt.PromptSupport;
import util.Combobox_design;
import util.JTextF_design;
import util.TinhThanhUtil;

/**
 *
 * @author kiman
 */
public class AddThiSinhDialog extends javax.swing.JDialog {
    ThiSinhPanel thisinhPanel;
    Combobox_design cbb_design = new Combobox_design();
    JTextF_design jtf_design = new JTextF_design();
    ThiSinhBUS thisinhBus = new ThiSinhBUS();
    /**
     * Creates new form AddThiSinhDialog
     */
    public AddThiSinhDialog(java.awt.Frame parent, boolean modal,ThiSinhPanel thisinhPanel) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Thêm thí sinh");
        this.thisinhPanel=thisinhPanel;
        khoiTao();
    }
    public void khoiTao(){
        setUpCBB();
        setUpJTF();
        setUpPlaceholder();
    }
    public void setUpJTF(){
        jtf_design.setUpJTF(jtf_cccd);
        jtf_design.setUpJTF(jtf_ho);
        jtf_design.setUpJTF(jpassword);
        jtf_design.setUpJTF(jtf_sbd);
        jtf_design.setUpJTF(jtf_ten);
        jtf_design.setUpJTF(jtf_sdt);
        jtf_design.setUpJTF(jtf_email);
        jcalendar_ns.setDate(new Date());
    }
    public void setUpCBB(){
        cbb_design.setUpComBoBox(cbb_noisinh);
        cbb_design.setUpComBoBox(cbb_gt);
        cbb_design.setUpComBoBox(cbb_kv);
        cbb_design.setUpComBoBox(cbb_doituong);
        cbb_gt.addItem("Tất cả");
        String[] gioitinhs = {"Nam", "Nữ"};
        for (String gt : gioitinhs) {
            cbb_gt.addItem(gt);
        }
        cbb_doituong.addItem("Tất cả");
        String[] dtuongs = {"Không","01","06a","06b"};
        for (String dt : dtuongs) {
            cbb_doituong.addItem(dt);
        }
        cbb_kv.addItem("Tất cả");
        String[] khuvucs = {"1", "2", "2NT", "3"};
        for (String kv : khuvucs) {
            cbb_kv.addItem(kv);
        }
        cbb_noisinh.addItem("Tất cả");
        for(String ns : TinhThanhUtil.getAllTinhThanh()){
            cbb_noisinh.addItem(ns);
        }
        
    }
    public void setUpPlaceholder() {
        PromptSupport.setPrompt("CCCD 12 số", jtf_cccd);
        PromptSupport.setForeground(Color.GRAY, jtf_cccd);
        PromptSupport.setFocusBehavior(PromptSupport.FocusBehavior.SHOW_PROMPT, jtf_cccd);
        PromptSupport.setPrompt("VD: Nguyễn", jtf_ho);
        PromptSupport.setForeground(Color.GRAY, jtf_ho);
        PromptSupport.setFocusBehavior(PromptSupport.FocusBehavior.SHOW_PROMPT, jtf_ho);
        PromptSupport.setPrompt("VD: Văn A", jtf_ten);
        PromptSupport.setForeground(Color.GRAY, jtf_ten);
        PromptSupport.setFocusBehavior(PromptSupport.FocusBehavior.SHOW_PROMPT, jtf_ten);
        PromptSupport.setPrompt("Gồm 10 số", jtf_sdt);
        PromptSupport.setForeground(Color.GRAY, jtf_sdt);
        PromptSupport.setFocusBehavior(PromptSupport.FocusBehavior.SHOW_PROMPT, jtf_email);
        PromptSupport.setPrompt("VD: admin@gmail.com", jtf_email);
        PromptSupport.setForeground(Color.GRAY, jtf_sdt);
        PromptSupport.setFocusBehavior(PromptSupport.FocusBehavior.SHOW_PROMPT, jtf_email);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtf_cccd = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtf_sbd = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jtf_ten = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jtf_sdt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jtf_email = new javax.swing.JTextField();
        cbb_noisinh = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cbb_gt = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        cbb_kv = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        cbb_doituong = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jcalendar_ns = new com.toedter.calendar.JDateChooser();
        jtf_ho = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jpassword = new javax.swing.JPasswordField();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("THÊM THÍ SINH");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(225, 225, 225)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(23, 23, 23))
        );

        jLabel3.setText("CCCD");

        jLabel4.setText("Số báo danh");

        jLabel5.setText("Họ");

        jLabel6.setText("Ngày sinh");

        jLabel7.setText("Giới tính");

        jLabel8.setText("Email");

        jLabel9.setText("Số điện thoại");

        jLabel10.setText("Nơi sinh");

        jLabel11.setText("Khu vực");

        jLabel12.setText("Đối tượng ưu tiên");

        jButton1.setBackground(new java.awt.Color(255, 0, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Hủy");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 153, 51));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Thêm");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel13.setText("Tên");

        jLabel14.setText("Mật khẩu");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(243, 243, 243)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jtf_cccd, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(110, 110, 110)
                        .addComponent(jtf_sbd, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLabel5)
                        .addGap(274, 274, 274)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jtf_ho, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(110, 110, 110)
                        .addComponent(jtf_ten, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jtf_sdt, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(110, 110, 110)
                        .addComponent(jtf_email, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(210, 210, 210)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(cbb_noisinh, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(110, 110, 110)
                        .addComponent(cbb_gt, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(234, 234, 234)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(cbb_kv, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(110, 110, 110)
                        .addComponent(cbb_doituong, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(231, 231, 231)
                                .addComponent(jLabel6))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jpassword)
                                    .addGap(110, 110, 110)
                                    .addComponent(jcalendar_ns, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(210, 210, 210)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(0, 54, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtf_cccd, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtf_sbd, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel13))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtf_ho, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtf_ten, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel14))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jpassword, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                    .addComponent(jcalendar_ns, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtf_sdt, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtf_email, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel7))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbb_noisinh, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbb_gt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbb_kv, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbb_doituong, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String cccd = jtf_cccd.getText().trim();
        String sbd = jtf_sbd.getText().trim();
        String ten = jtf_ten.getText();
        String ho = jtf_ho.getText();
        char[] password = jpassword.getPassword();
        String pass = new String(password);
        String doituong = (String) cbb_doituong.getSelectedItem();
        String gioitinh = (String) cbb_gt.getSelectedItem();
        String dt = jtf_sdt.getText().trim();
        String email = jtf_email.getText().trim();
        String noisinh = (String) cbb_noisinh.getSelectedItem();
        String khuvuc = (String) cbb_kv.getSelectedItem();
        if (cccd == null || cccd.trim().isEmpty() || cccd.length() != 12) {
            javax.swing.JOptionPane.showMessageDialog(this, "CCCD không hợp lệ");
            return;
        }
        if (ten == null || ten.trim().isEmpty() || ho == null || ho.trim().isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Vui lòng nhập họ tên");
            return;
        }
        if (pass == null || pass.trim().isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Vui lòng nhập mật khẩu");
            return;
        }
        Date ngaysinh = jcalendar_ns.getDate();
        if (!dt.equals("")) {
            if (!dt.matches("^0\\d{9}$")) {
                javax.swing.JOptionPane.showMessageDialog(this, "Số điện thoại không đúng định dạng");
                return;
            }
        }
        if (!email.equals("")) {
            if (!email.matches("^[A-Za-z0-9+_.-]+@[A-Za-z0-9.-]+$")) {
                javax.swing.JOptionPane.showMessageDialog(this, "Email không đúng định dạng");
                return;
            }
        }
        if (ngaysinh == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "Vui lòng chọn ngày sinh");
            return;
        }

// Lấy năm
        Calendar cal = Calendar.getInstance();
        cal.setTime(ngaysinh);
        int nam = cal.get(Calendar.YEAR);

// Check năm > 2008
        if (nam > 2008) {
            javax.swing.JOptionPane.showMessageDialog(this, "Năm sinh phải <= 2008");
            return;
        }
        if (noisinh == null || noisinh.trim().isEmpty() || noisinh.equals("Tất cả")) {
            javax.swing.JOptionPane.showMessageDialog(this, "Vui lòng chọn nơi sinh");
            return;
        }
        if (gioitinh == null || gioitinh.trim().isEmpty() || gioitinh.equals("Tất cả")) {
            javax.swing.JOptionPane.showMessageDialog(this, "Vui lòng chọn giới tính");
            return;
        }
        if (khuvuc == null || khuvuc.trim().isEmpty() || khuvuc.equals("Tất cả")) {
            javax.swing.JOptionPane.showMessageDialog(this, "Vui lòng chọn đối tượng khu vực");
            return;
        }
        if (doituong == null || doituong.trim().isEmpty() || doituong.equals("Tất cả")) {
            javax.swing.JOptionPane.showMessageDialog(this, "Vui lòng chọn đối tượng ưu tiên");
            return;
        }
        if(doituong.equals("Không"))
            doituong = null;
        if(email.trim().equals(""))
            email = null;
        if(dt.trim().equals(""))
            dt = null;
        if(sbd.trim().equals(""))
            sbd = null;
        ThiSinhDTO thisinh = new ThiSinhDTO();
        thisinh.setCccd(cccd);
        thisinh.setSobaodanh(sbd);
        thisinh.setHo(ho);
        thisinh.setTen(ten);
        thisinh.setPassword(pass);
        thisinh.setNgaySinh(ngaysinh);
        thisinh.setGioiTinh(gioitinh);
        thisinh.setKhuVuc(khuvuc);
        thisinh.setDoiTuong(doituong);
        thisinh.setEmail(email);
        thisinh.setDienThoai(dt);
        thisinh.setNoiSinh(noisinh);
        if (thisinhBus.insert(thisinh) == 1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Thêm thành công");
        }
        ArrayList<ThiSinhDTO> thisinhList = thisinhBus.getAll();
        thisinhPanel.loadDataTable(thisinhList);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbb_doituong;
    private javax.swing.JComboBox<String> cbb_gt;
    private javax.swing.JComboBox<String> cbb_kv;
    private javax.swing.JComboBox<String> cbb_noisinh;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private com.toedter.calendar.JDateChooser jcalendar_ns;
    private javax.swing.JPasswordField jpassword;
    private javax.swing.JTextField jtf_cccd;
    private javax.swing.JTextField jtf_email;
    private javax.swing.JTextField jtf_ho;
    private javax.swing.JTextField jtf_sbd;
    private javax.swing.JTextField jtf_sdt;
    private javax.swing.JTextField jtf_ten;
    // End of variables declaration//GEN-END:variables
}
