/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package GUIDialog;

import BUS.NganhBUS;
import BUS.PermissionBUS;
import BUS.ToHopBUS;
import BUS.UserBUS;
import DTO.NganhDTO;
import DTO.RoleDTO;
import DTO.UserDTO;
import GUI.Panel.UserPanel;
import com.formdev.flatlaf.extras.FlatSVGIcon;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Set;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import util.Combobox_design;

/**
 *
 * @author kiman
 */
public class AddUser extends javax.swing.JDialog {
    UserPanel userPanel;
    UserBUS userBus = new  UserBUS();
    Combobox_design cbb_design = new Combobox_design();
    JCheckBox chk_showPassword;
    private ArrayList<JCheckBox> roleCheckboxes =
        new ArrayList<>();
    /**
     * Creates new form AddNganhDialog
     */
    public AddUser(java.awt.Frame parent, boolean modal, UserPanel userPanel) {
       super(parent, modal);
    initComponents();
    
    // UI password có icon mắt
    jPanel2.remove(jPasswordField1);
    addPasswordField();
    this.userPanel = userPanel;
    addRoleCheckboxes();

    // setup combobox role
    setLocationRelativeTo(null); // hiển thị giữa màn hình
    }
    
    private void addPasswordField() {
    JPanel passwordPanel = new JPanel(null);

    // ===== Password field =====
    jPasswordField1 = new javax.swing.JPasswordField();
    jPasswordField1.setBounds(0, 0, 180, 30);
    jPasswordField1.setEchoChar('*'); // mặc định ẩn

    // ===== Icon =====
      FlatSVGIcon iconEye = new FlatSVGIcon("./resources/icon/eye.svg", 16, 16);
    FlatSVGIcon iconUnEye = new FlatSVGIcon("./resources/icon/un-eye.svg", 16, 16);

    JButton btn_eye = new JButton(iconEye);
    btn_eye.setBounds(180, 0, 40, 30);

    // fix UI
    btn_eye.setBorder(null);
    btn_eye.setContentAreaFilled(false);
    btn_eye.setFocusPainted(false);

    // đảm bảo icon không bị méo
    btn_eye.setHorizontalAlignment(JButton.CENTER);
    btn_eye.setVerticalAlignment(JButton.CENTER);

    // ===== Toggle =====
    final boolean[] isVisible = {false};

    btn_eye.addActionListener(e -> {
        if (isVisible[0]) {
            jPasswordField1.setEchoChar('*');
            btn_eye.setIcon(iconUnEye);
        } else {
            jPasswordField1.setEchoChar((char) 0);
            btn_eye.setIcon(iconEye);
        }
        isVisible[0] = !isVisible[0];
    });

    // ===== Add vào panel =====
    passwordPanel.add(jPasswordField1);
    passwordPanel.add(btn_eye);

    passwordPanel.setBounds(140, 90, 220, 30);
    jPanel2.add(passwordPanel);
}
    private void addRoleCheckboxes() {

    PermissionBUS permissionBUS =
            new PermissionBUS();

    ArrayList<RoleDTO> roles =
            permissionBUS.getAllRole();

    javax.swing.JLabel lbRole =
            new javax.swing.JLabel("Vai trò");

    lbRole.setBounds(50, 155, 70, 20);

    jPanel2.add(lbRole);

    int x = 140;
    int y = 150;

    for (RoleDTO role : roles) {

        JCheckBox chk =
                new JCheckBox(
                        role.getRoleName()
                );

        chk.setBackground(java.awt.Color.WHITE);

        chk.putClientProperty(
                "role",
                role
        );

        chk.setBounds(x, y, 100, 25);

        roleCheckboxes.add(chk);

        jPanel2.add(chk);

        x += 110;

        // xuống dòng nếu quá dài
        if (x > 330) {

            x = 140;

            y += 30;
        }
    }

    jPanel2.repaint();

    jPanel2.revalidate();
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtf_username = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(224, 224, 224));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Thêm người dùng");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        jLabel2.setText("Tên tài khoản");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(50, 50, 90, 16);

        jLabel3.setText("Mật khẩu");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(50, 100, 70, 16);

        jtf_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_usernameActionPerformed(evt);
            }
        });
        jPanel2.add(jtf_username);
        jtf_username.setBounds(140, 40, 220, 31);

        jButton1.setBackground(new java.awt.Color(51, 204, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Lưu thông tin");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(260, 220, 110, 40);

        jButton2.setBackground(new java.awt.Color(255, 0, 0));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Hủy");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);
        jButton2.setBounds(60, 220, 90, 40);

        jPasswordField1.setText("jPasswordField1");
        jPanel2.add(jPasswordField1);
        jPasswordField1.setBounds(140, 90, 220, 30);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(146, 146, 146))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
           
    String username = jtf_username.getText().trim();
    String password = new String(jPasswordField1.getPassword()).trim();

    // ===== Validate =====
    if (username.isEmpty() || password.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông tin!");
        return;
    }
// ===== role =====
Set<RoleDTO> roles =
        new HashSet<>();

for (JCheckBox chk : roleCheckboxes) {

    if (chk.isSelected()) {

        RoleDTO role =
                (RoleDTO) chk.getClientProperty("role");

        roles.add(role);
    }
}

if (roles.isEmpty()) {

    JOptionPane.showMessageDialog(
            this,
            "Vui lòng chọn ít nhất 1 role!"
    );

    return;
}
    // ===== Tạo DTO =====
    UserDTO user = new UserDTO();
    user.setUsername(username);
    user.setPassword(password);
    user.setRoles(roles);
    user.setEnabled(true);
    
    // ===== Gọi BUS =====
    String message = userBus.insert(user);
    if(message.equals("OK")){
        JOptionPane.showMessageDialog(this, "Thêm thành công!");
         userPanel.loadData();
        this.dispose();
    }else{
        JOptionPane.showMessageDialog(this, message);
    }
   
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
     this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jtf_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_usernameActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jtf_username;
    // End of variables declaration//GEN-END:variables
}
