package GUIDialog;

import BUS.NganhBUS;
import BUS.ToHopBUS;
import DTO.NganhDTO;
import GUI.Panel.NganhPanel;

public class DetailNganhDialog extends javax.swing.JDialog {
    NganhDTO nganhDto;
    NganhPanel nganhPanel;
    NganhBUS nganhBus = new NganhBUS();
    ToHopBUS tohopBus = new ToHopBUS();
    public DetailNganhDialog(java.awt.Frame parent, boolean modal, NganhPanel nganhPanel, NganhDTO nganhDto, String SLDK) {
        super(parent, modal);
        initComponents();
        this.setTitle("Xem chi tiết ngành");
        jtf_slnv.setText(SLDK);
        this.setLocationRelativeTo(null);
        this.nganhPanel=nganhPanel;
        this.nganhDto = nganhDto;
        khoiTao();
    }
    public void khoiTao() {
        toggleInputs();
        setData();
    }

    public void setData() {
        if (nganhDto == null) {
            return;
        }

        jtf_manganh.setText(nganhDto.getMaNganh());
        jtf_tennganh.setText(nganhDto.getTenNganh());
        jtf_chitieu.setText(String.valueOf(nganhDto.getNChiTieu()));

        // Điểm sàn
        if (nganhDto.getNDiemSan() != null) {
            jtf_đtt_đgnl.setText(nganhDto.getNDiemSan().toString());
        }

        // Combobox tổ hợp
        jtf_tohop.setText(nganhDto.getNToHopGoc());

        // Checkbox
        jcheck_tuyenthang.setSelected("Y".equals(nganhDto.getNTuyenThang()));
        jcheck_dgnl.setSelected("Y".equals(nganhDto.getNDGNL()));
        jcheck_thpt.setSelected("Y".equals(nganhDto.getNTHPT()));
        jcheck_vsat.setSelected("Y".equals(nganhDto.getNVSAT()));
        jtf_dtt_vsat.setText(nganhDto.getNDiemTrungTuyenVSAT() != null ? String.valueOf(nganhDto.getNDiemTrungTuyenVSAT()) : "");
        jtf_đtt_đgnl.setText(nganhDto.getNDiemTrungTuyenDGNL() != null ? String.valueOf(nganhDto.getNDiemTrungTuyenDGNL()) : "");

        // Số lượng
        jtf_sltt.setText(nganhDto.getSlXTT() == null ? "" : nganhDto.getSlXTT().toString());
        jtf_dgnl.setText(nganhDto.getSlDGNL() == null ? "" : nganhDto.getSlDGNL().toString());
        jtf_thpt.setText(nganhDto.getSlTHPT() == null ? "" : nganhDto.getSlTHPT().toString());
        jtf_vsat.setText(nganhDto.getSlVSAT() == null ? "" : nganhDto.getSlVSAT().toString());
        jtf_dtt.setText(nganhDto.getNDiemTrungTuyen() == null ? "" : nganhDto.getNDiemTrungTuyen().toString());
        toggleInputs();
    }

    public void toggleInputs() {
        if (!jcheck_tuyenthang.isSelected()) {
            jtf_sltt.setText("");
        }
        if (!jcheck_dgnl.isSelected()) {
            jtf_dgnl.setText("");
        }
        if (!jcheck_thpt.isSelected()) {
            jtf_thpt.setText("");
        }
        if (!jcheck_vsat.isSelected()) {
            jtf_vsat.setText("");
        }

        jtf_sltt.setEnabled(jcheck_tuyenthang.isSelected());
        jtf_dgnl.setEnabled(jcheck_dgnl.isSelected());
        jtf_thpt.setEnabled(jcheck_thpt.isSelected());
        jtf_vsat.setEnabled(jcheck_vsat.isSelected());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jtf_sltt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jtf_chitieu = new javax.swing.JTextField();
        jtf_tennganh = new javax.swing.JTextField();
        jcheck_dgnl = new javax.swing.JCheckBox();
        jcheck_tuyenthang = new javax.swing.JCheckBox();
        jcheck_vsat = new javax.swing.JCheckBox();
        jcheck_thpt = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        jtf_vsat = new javax.swing.JTextField();
        jtf_manganh = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jtf_dgnl = new javax.swing.JTextField();
        jtf_thpt = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jtf_đtt_đgnl = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jtf_tohop = new javax.swing.JTextField();
        jtf_dtt = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jtf_diemsan1 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jtf_slnv = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jtf_dtt_vsat = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(245, 245, 245));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Xem chi tiết ngành tuyển sinh");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(197, 197, 197)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        jLabel2.setText("Mã ngành");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(30, 40, 54, 16);

        jtf_sltt.setEditable(false);
        jPanel2.add(jtf_sltt);
        jtf_sltt.setBounds(460, 30, 150, 31);

        jLabel3.setText("Tên ngành");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(30, 100, 70, 16);

        jLabel4.setText("Tổ hợp gốc");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(30, 160, 90, 16);

        jLabel5.setText("Chỉ tiêu");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(40, 220, 41, 16);

        jtf_chitieu.setEditable(false);
        jPanel2.add(jtf_chitieu);
        jtf_chitieu.setBounds(120, 210, 150, 32);

        jtf_tennganh.setEditable(false);
        jPanel2.add(jtf_tennganh);
        jtf_tennganh.setBounds(120, 90, 150, 32);

        jcheck_dgnl.setText("ĐGNL");
        jcheck_dgnl.addActionListener(this::jcheck_dgnlActionPerformed);
        jPanel2.add(jcheck_dgnl);
        jcheck_dgnl.setBounds(190, 400, 97, 36);

        jcheck_tuyenthang.setText("Tuyển thẳng");
        jcheck_tuyenthang.addActionListener(this::jcheck_tuyenthangActionPerformed);
        jPanel2.add(jcheck_tuyenthang);
        jcheck_tuyenthang.setBounds(40, 400, 97, 36);

        jcheck_vsat.setText("VSAT");
        jcheck_vsat.addActionListener(this::jcheck_vsatActionPerformed);
        jPanel2.add(jcheck_vsat);
        jcheck_vsat.setBounds(480, 400, 92, 36);

        jcheck_thpt.setText("THPT");
        jcheck_thpt.addActionListener(this::jcheck_thptActionPerformed);
        jPanel2.add(jcheck_thpt);
        jcheck_thpt.setBounds(340, 400, 95, 36);

        jLabel6.setText("SL Tuyển Thẳng");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(350, 40, 100, 16);

        jtf_vsat.setEditable(false);
        jPanel2.add(jtf_vsat);
        jtf_vsat.setBounds(460, 210, 150, 31);

        jtf_manganh.setEditable(false);
        jPanel2.add(jtf_manganh);
        jtf_manganh.setBounds(120, 30, 150, 31);

        jLabel7.setText("Điểm trúng tuyển THPT");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(320, 280, 130, 16);

        jLabel8.setText("SL  ĐGNL");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(350, 100, 60, 16);

        jtf_dgnl.setEditable(false);
        jPanel2.add(jtf_dgnl);
        jtf_dgnl.setBounds(460, 90, 150, 31);

        jtf_thpt.setEditable(false);
        jPanel2.add(jtf_thpt);
        jtf_thpt.setBounds(460, 150, 150, 31);

        jLabel9.setText("SL THPT");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(350, 160, 100, 16);

        jLabel10.setText("Điểm trúng tuyển ĐGNL");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(470, 330, 130, 16);

        jtf_đtt_đgnl.setEditable(false);
        jPanel2.add(jtf_đtt_đgnl);
        jtf_đtt_đgnl.setBounds(470, 350, 150, 30);

        jButton2.setBackground(new java.awt.Color(255, 0, 0));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Thoát");
        jButton2.addActionListener(this::jButton2ActionPerformed);
        jPanel2.add(jButton2);
        jButton2.setBounds(280, 460, 90, 30);

        jtf_tohop.setEditable(false);
        jPanel2.add(jtf_tohop);
        jtf_tohop.setBounds(120, 150, 150, 30);

        jtf_dtt.setEditable(false);
        jPanel2.add(jtf_dtt);
        jtf_dtt.setBounds(460, 270, 150, 31);

        jLabel11.setText("SL VSAT");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(350, 220, 100, 16);

        jLabel12.setText("Điểm sàn");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(40, 280, 60, 16);

        jtf_diemsan1.setEditable(false);
        jPanel2.add(jtf_diemsan1);
        jtf_diemsan1.setBounds(120, 270, 150, 30);

        jLabel13.setText("Số lượng nguyện vọng");
        jPanel2.add(jLabel13);
        jLabel13.setBounds(260, 330, 130, 16);

        jtf_slnv.setEditable(false);
        jPanel2.add(jtf_slnv);
        jtf_slnv.setBounds(260, 350, 150, 30);

        jLabel14.setText("Điểm trúng tuyển V-SAT");
        jPanel2.add(jLabel14);
        jLabel14.setBounds(30, 330, 130, 16);

        jtf_dtt_vsat.setEditable(false);
        jPanel2.add(jtf_dtt_vsat);
        jtf_dtt_vsat.setBounds(30, 350, 150, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 648, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jcheck_tuyenthangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcheck_tuyenthangActionPerformed
        jcheck_tuyenthang.addActionListener(e -> {
        // Luôn giữ nguyên trạng thái cũ bất chấp người dùng click
        jcheck_tuyenthang.setSelected(!jcheck_tuyenthang.isSelected()); 
        });
    }//GEN-LAST:event_jcheck_tuyenthangActionPerformed

    private void jcheck_dgnlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcheck_dgnlActionPerformed
        jcheck_dgnl.addActionListener(e -> {
        // Luôn giữ nguyên trạng thái cũ bất chấp người dùng click
        jcheck_dgnl.setSelected(!jcheck_dgnl.isSelected()); 
        });
    }//GEN-LAST:event_jcheck_dgnlActionPerformed

    private void jcheck_thptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcheck_thptActionPerformed
        jcheck_thpt.addActionListener(e -> {
        // Luôn giữ nguyên trạng thái cũ bất chấp người dùng click
        jcheck_thpt.setSelected(!jcheck_thpt.isSelected()); 
        });
    }//GEN-LAST:event_jcheck_thptActionPerformed

    private void jcheck_vsatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcheck_vsatActionPerformed
        jcheck_vsat.addActionListener(e -> {
        // Luôn giữ nguyên trạng thái cũ bất chấp người dùng click
        jcheck_vsat.setSelected(!jcheck_vsat.isSelected()); 
        });
    }//GEN-LAST:event_jcheck_vsatActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JCheckBox jcheck_dgnl;
    private javax.swing.JCheckBox jcheck_thpt;
    private javax.swing.JCheckBox jcheck_tuyenthang;
    private javax.swing.JCheckBox jcheck_vsat;
    private javax.swing.JTextField jtf_chitieu;
    private javax.swing.JTextField jtf_dgnl;
    private javax.swing.JTextField jtf_diemsan1;
    private javax.swing.JTextField jtf_dtt;
    private javax.swing.JTextField jtf_dtt_vsat;
    private javax.swing.JTextField jtf_manganh;
    private javax.swing.JTextField jtf_slnv;
    private javax.swing.JTextField jtf_sltt;
    private javax.swing.JTextField jtf_tennganh;
    private javax.swing.JTextField jtf_thpt;
    private javax.swing.JTextField jtf_tohop;
    private javax.swing.JTextField jtf_vsat;
    private javax.swing.JTextField jtf_đtt_đgnl;
    // End of variables declaration//GEN-END:variables
}
