/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package GUIDialog;

import BUS.ThiSinhBUS;
import DTO.ThiSinhDTO;
import GUI.Panel.ThiSinhPanel;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import util.Combobox_design;
import util.TinhThanhUtil;

/**
 *
 * @author kiman
 */
public class UpdateThiSinhDialog extends javax.swing.JDialog {
    ThiSinhBUS thisinhBus = new ThiSinhBUS();
    ThiSinhPanel thisinhPanel = new ThiSinhPanel();
    Combobox_design cbb_design = new Combobox_design();
    ThiSinhDTO thisinh;
    /**
     * Creates new form UpdateThiSinhDialog
     */
    public UpdateThiSinhDialog(java.awt.Frame parent, boolean modal, ThiSinhPanel thisinhPanel, ThiSinhDTO thisinh) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Cập nhật thí sinh");
        this.thisinhPanel = thisinhPanel;
        this.thisinh=thisinh;
        khoiTao();
        
    }
    public void khoiTao() {
        setUpCbb();
        setData();
    }
    public void setData() {
        jtf_cccd.setText(thisinh.getCccd());
        jtf_hoten.setText(thisinh.getHoTen());
        jtf_sbd.setText(thisinh.getSobaodanh());
        jtf_sdt.setText(thisinh.getDienThoai());

        jcalendar_ns.setDate(thisinh.getNgaySinh());
        if (thisinh.getDoiTuong().equals("")) {
            cbb_doituong.setSelectedItem("Không");
        } else {
            cbb_doituong.setSelectedItem(thisinh.getDoiTuong());
        }
        cbb_kv.setSelectedItem(thisinh.getKhuVuc());
        cbb_noisinh.setSelectedItem(thisinh.getNoiSinh());
        cbb_gt.setSelectedItem(thisinh.getGioiTinh());
        jtf_email.setText(thisinh.getEmail());
    }
    public void setUpCbb() {
        cbb_design.setUpComBoBox(cbb_gt);
        cbb_design.setUpComBoBox(cbb_doituong);
        cbb_design.setUpComBoBox(cbb_kv);
        cbb_design.setUpComBoBox(cbb_noisinh);
        String[] areas = {"1", "2", "2NT", "3"};
        for (String a : areas) {
            cbb_kv.addItem(a);
        }
        String[] gioitinhs = {"Nam", "Nữ"};
        for (String gt : gioitinhs) {
            cbb_gt.addItem(gt);
        }
        for (String tt : TinhThanhUtil.getAllTinhThanh()) {
            cbb_noisinh.addItem(tt);
        }
        String[] dtuongs = {"Không","01", "06a", "06b"};
        for (String dt : dtuongs) {
            cbb_doituong.addItem(dt);
        }

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        logo_edit = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtf_cccd = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtf_sbd = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jtf_hoten = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jtf_sdt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jtf_email = new javax.swing.JTextField();
        cbb_noisinh = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        btn_cancel = new javax.swing.JButton();
        cbb_doituong = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        cbb_kv = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        cbb_gt = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        btn_update = new javax.swing.JButton();
        jcalendar_ns = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("CẬP NHẬT THÍ SINH");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(logo_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logo_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jLabel3.setText("CCCD");

        jLabel4.setText("Số báo danh");

        jLabel5.setText("Họ và tên");

        jLabel6.setText("Ngày sinh");

        jLabel7.setText("Giới tính");

        jLabel8.setText("Email");

        jLabel9.setText("Số điện thoại");

        btn_cancel.setBackground(new java.awt.Color(255, 0, 0));
        btn_cancel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_cancel.setForeground(new java.awt.Color(255, 255, 255));
        btn_cancel.setText("Hủy");
        btn_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelActionPerformed(evt);
            }
        });

        jLabel12.setText("Đối tượng ưu tiên");

        jLabel11.setText("Khu vực");

        jLabel10.setText("Nơi sinh");

        btn_update.setBackground(new java.awt.Color(0, 153, 51));
        btn_update.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_update.setForeground(new java.awt.Color(255, 255, 255));
        btn_update.setText("Cập nhật");
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(255, 255, 255)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jtf_cccd, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(121, 121, 121)
                        .addComponent(jtf_sbd, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(221, 221, 221)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jtf_sdt, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(121, 121, 121)
                        .addComponent(jtf_email, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(220, 220, 220)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(cbb_noisinh, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(120, 120, 120)
                        .addComponent(cbb_gt, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(244, 244, 244)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(cbb_kv, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(120, 120, 120)
                        .addComponent(cbb_doituong, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(btn_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61)
                        .addComponent(btn_update))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jtf_hoten, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(122, 122, 122)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jcalendar_ns, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(0, 29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jtf_cccd, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jtf_sbd, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtf_hoten, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                    .addComponent(jcalendar_ns, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel8)))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtf_sdt, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtf_email, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel7))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbb_noisinh, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbb_gt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbb_kv, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbb_doituong, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_update, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_btn_cancelActionPerformed

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
        String cccd = jtf_cccd.getText().trim();
        String sbd = jtf_sbd.getText().trim();
        String hoten = jtf_hoten.getText();
        String doituong = (String) cbb_doituong.getSelectedItem();
        String gioitinh = (String) cbb_gt.getSelectedItem();
        String dt = jtf_sdt.getText().trim();
        String email = jtf_email.getText().trim();
        String noisinh = (String) cbb_noisinh.getSelectedItem();
        String khuvuc = (String) cbb_kv.getSelectedItem();
        if (cccd == null || cccd.trim().isEmpty() || cccd.length() != 12) {
            javax.swing.JOptionPane.showMessageDialog(this, "CCCD không hợp lệ");
            return;
        }
        if (hoten == null || hoten.trim().isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Vui lòng nhập họ tên");
            return;
        }
        Date ngaysinh = jcalendar_ns.getDate();

        if (ngaysinh == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "Vui lòng chọn ngày sinh");
            return;
        }
        

        // Lấy năm
        Calendar cal = Calendar.getInstance();
        cal.setTime(ngaysinh);
        int nam = cal.get(Calendar.YEAR);

        // Check năm > 2008
        if (nam > 2008) {
            javax.swing.JOptionPane.showMessageDialog(this, "Năm sinh phải <= 2008");
            return;
        }
        
        if (!dt.equals("")) {
            if (!dt.matches("^0\\d{9}$")) {
                javax.swing.JOptionPane.showMessageDialog(this, "Số điện thoại không đúng định dạng");
                return;
            }
        }
        if (!email.equals("")) {
            if (!email.matches("^[A-Za-z0-9+_.-]+@[A-Za-z0-9.-]+$")) {
                javax.swing.JOptionPane.showMessageDialog(this, "Email không đúng định dạng");
                return;
            }
        }
        
        if (noisinh == null || noisinh.trim().isEmpty() || noisinh.equals("Tất cả")) {
            javax.swing.JOptionPane.showMessageDialog(this, "Vui lòng chọn nơi sinh");
            return;
        }
        if (gioitinh == null || gioitinh.trim().isEmpty() || gioitinh.equals("Tất cả")) {
            javax.swing.JOptionPane.showMessageDialog(this, "Vui lòng chọn giới tính");
            return;
        }
        if (khuvuc == null || khuvuc.trim().isEmpty() || khuvuc.equals("Tất cả")) {
            javax.swing.JOptionPane.showMessageDialog(this, "Vui lòng chọn đối tượng khu vực");
            return;
        }
        if (doituong == null || doituong.trim().isEmpty() || doituong.equals("Tất cả")) {
            javax.swing.JOptionPane.showMessageDialog(this, "Vui lòng chọn đối tượng ưu tiên");
            return;
        }
        thisinh.setCccd(cccd);
        thisinh.setSobaodanh(sbd);
        thisinh.setTen(hoten);
        thisinh.setNgaySinh(ngaysinh);
        thisinh.setGioiTinh(gioitinh);
        thisinh.setKhuVuc(khuvuc);
        if (doituong.equals("Không"))
            thisinh.setDoiTuong(null);
        else {
            thisinh.setDoiTuong(doituong);
        }
        thisinh.setEmail(email);
        thisinh.setDienThoai(dt);
        thisinh.setNoiSinh(noisinh);
        if (thisinhBus.update(thisinh) == 1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Cập nhật hồ sơ thành công");
        }
        ArrayList<ThiSinhDTO> thisinhList = thisinhBus.getAll();
        thisinhPanel.loadDataTable(thisinhList);
        this.dispose();
    }//GEN-LAST:event_btn_updateActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancel;
    private javax.swing.JButton btn_update;
    private javax.swing.JComboBox<String> cbb_doituong;
    private javax.swing.JComboBox<String> cbb_gt;
    private javax.swing.JComboBox<String> cbb_kv;
    private javax.swing.JComboBox<String> cbb_noisinh;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private com.toedter.calendar.JDateChooser jcalendar_ns;
    private javax.swing.JTextField jtf_cccd;
    private javax.swing.JTextField jtf_email;
    private javax.swing.JTextField jtf_hoten;
    private javax.swing.JTextField jtf_sbd;
    private javax.swing.JTextField jtf_sdt;
    private javax.swing.JLabel logo_edit;
    // End of variables declaration//GEN-END:variables
}
